languages:
  Ruby: true
exclude_paths:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "pender-client-php"
- "public/coverage"
- "test"
- "public/javascripts/jquery-2.1.3.min.js"
