version: "2.1"
volumes:
  redis:
networks:
  dev:
services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    networks:
      - dev
  pender:
    build: .
    shm_size: 1G
    ports:
      - "3200:3200"
      - "9555:9555"
    volumes:
      - ".:/app"
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
    networks:
      - dev
